on:
  push:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: composer install
      - run: composer lint
      - run: cd private && corepack enable && yarn && yarn lint && cd ..
  build:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --classmap-authoritative
      - run: composer du -o
      - run: cd private && corepack enable && yarn && yarn build && cd ..
      - run: zip -r humanity-salesforce-connector-develop.zip ./ -x docs\* -x private\* -x vendor\* -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x GOVERNANCE.md -x LICENSE.md -x phpcs.xml -x phpstan.neon -x SECURITY.md
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: humanity-salesforce-connector-develop.zip
          target_commitish: main
